name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * SUN'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Dockerfiles with hadolint
        run: |
          find . -type f -print0 | grep -z -E 'Dockerfile(\..*)?$' | xargs -0 -I {} docker run --rm -i hadolint/hadolint < {}

      - name: Lint shell scripts with ShellCheck
        run: |
          find . -type f -exec grep -Iq '^#!' {} \; -print0 | xargs -0 -I {} docker run --rm -v "$PWD:/scripts" koalaman/shellcheck /scripts/{}

  docker_build:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        wine_branch:
          - stable
          - devel
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export to local Docker instance
        uses: docker/build-push-action@v4
        with:
          build-args: |
            WINE_BRANCH=${{ matrix.wine_branch }}
          load: true
          tags: docker-wine:latest

      - name: Test
        run: |
          ./docker-wine --local --rm --xvfb --notty winetricks -q dotnet40

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract wine version
        id: wine_version
        env:
          WINE_BRANCH: ${{ matrix.wine_branch }}
        run: |
          WINE_VERSION="$(docker run --rm docker-wine /bin/bash -c "wine --version | sed -E 's/^wine-//'")"
          echo "WINE_VERSION=${WINE_VERSION}" | tee -a "$GITHUB_OUTPUT"

      - name: Generate timestamp
        id: timestamp
        run: |
          echo "TIMESTAMP=$(date +"%Y%m%d")" | tee -a "$GITHUB_OUTPUT"

      - name: Determine tags
        uses: haya14busa/action-cond@v1
        id: tags
        with:
          cond: ${{ matrix.wine_branch == 'stable' }}
          if_true: |
            scottyhardy/docker-wine:latest,
            scottyhardy/docker-wine:${{ matrix.wine_branch }},
            scottyhardy/docker-wine:${{ matrix.wine_branch }}-${{ steps.wine_version.outputs.WINE_VERSION }},
            scottyhardy/docker-wine:${{ matrix.wine_branch }}-${{ steps.wine_version.outputs.WINE_VERSION }}-${{ steps.timestamp.outputs.value }}
          if_false: |
            scottyhardy/docker-wine:${{ matrix.wine_branch }},
            scottyhardy/docker-wine:${{ matrix.wine_branch }}-${{ steps.wine_version.outputs.WINE_VERSION }},
            scottyhardy/docker-wine:${{ matrix.wine_branch }}-${{ steps.wine_version.outputs.WINE_VERSION }}-${{ steps.timestamp.outputs.value }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          build-args: |
            WINE_BRANCH=${{ matrix.wine_branch }}
          push: true
          tags: ${{ steps.tags.outputs.value }}

      - name: Update Docker Hub repository description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: scottyhardy/docker-wine
